
connection: jdbc:oracle:thin:tiger/scott@localhost:1521:productDB
directory: /Users/fcausa/tmp
entities:
   EXPORT_TAB_MEMO:
      skip: true #true or flase (optional)
      namespace: schema
      query: select * from table
      description: prova descrizione
      skip: false
   PRODUCT:
      query: select * from product
files:
  file1:
    file: /Users/tmp/file.txt
    column: 
       - id
       - company
       